<#
.SYNOPSIS
Compiles a BSP file from a VMF.

.DESCRIPTION
Compiles a BSP file from a VMF using the Source tool VBSP.

.PARAMETER Path
Path to the VMF to be compiled.
.PARAMETER OnlyEnts
This option causes vbsp only import the entities from the .vmf file. -OnlyEnts won't reimport brush models.
.PARAMETER OnlyProps
Only update the static props and detail props.
.PARAMETER GLView
Writes .gl files in the current directory that can be viewed with the glview tool.
.PARAMETER NoDetail
Get rid of all detail geometry. The geometry left over is what affects visibility.
.PARAMETER NoWater
Get rid of water brushes.
.PARAMETER LowPriority
Run as an idle-priority process.
.PARAMETER PackDirectory
Embeds the contents of <directory> in the packfile.

.PARAMETER NumThreads
Control the number of threads New-BSP uses (defaults to the # of processors on your machine).
.PARAMETER VerboseEntities
If -Verbose is on, this disables verbose output for submodels.
.PARAMETER NoWeld
Don't join face vertices together.
.PARAMETER NoCsg
Don't chop out intersecting brush areas.
.PARAMETER NoShare
Emit unique face edges instead of sharing them.
.PARAMETER NoTJunc
Don't fixup t-junctions.
.PARAMETER NoOpt
By default, New-BSP removes the 'outer shell' of the map, which are all the faces you can't see because you can never get outside the map. -NoOpt disables this behaviour.
.PARAMETER NoPrune
Don't prune neighboring solid nodes.
.PARAMETER NoMerge
Don't merge together chopped faces on nodes.
.PARAMETER NoMergeWater
Don't merge together chopped faces on water.
.PARAMETER NoSubDiv
Don't subdivide faces for lightmapping.
.PARAMETER FullDetail
Mark all detail geometry as normal geometry (so all detail geometry will affect visibility).
.PARAMETER AllDetail
Convert all structural brushes to detail brushes, except func_brush entities whose names begin with structure_.
.PARAMETER LeakTest
Stop processing the map if a leak is detected. Whether or not this flag is set, a leak file will be written out at <vmf filename>.lin, and it can be imported into Hammer.
.PARAMETER BumpAll
Force all surfaces to be bump mapped.
.PARAMETER SnapAxial
Snap axial planes to integer coordinates.
.PARAMETER Block
Control the grid size mins that New-BSP chops the level on.
.PARAMETER Blocks
Enter the mins and maxs for the grid size New-BSP uses.
.PARAMETER BlockSize
Control the size of each grid square that New-BSP chops the level on.  Default is 1024.
.PARAMETER DumpStaticProps
Dump static props to staticprop*.txt
.PARAMETER DumpCollide
Write files with collision info.
.PARAMETER ForceSkyVis
Enable vis calculations in 3d skybox leaves
.PARAMETER LuxelScale
Scale all lightmaps by this amount (default: 1.0).
.PARAMETER MinLuxelScale
No luxel scale will be lower than this amount (default: 1.0).
.PARAMETER LightIfMissing
Force lightmaps to be generated for all surfaces even if they don't need lightmaps.
.PARAMETER LocalPhysX
To do: Currently unknown.
.PARAMETER KeepStaleZip
Keep the BSP's zip files intact but regenerate everything else.
.PARAMETER VirtualDispPhysics
Use virtual (not precomputed) displacement collision models
.PARAMETER VisGranulatiry
Force visibility splits # of units along X, Y, Z. CSGO branch only.
.PARAMETER Xbox
Enable mandatory xbox options.
Enables nodraw triggers, and disables water lighting.
.PARAMETER Xbox360
Generate Xbox360 version of vsp
.PARAMETER AllowDetailCracks
Allow detail cracks
.PARAMETER NoVirtualMesh
No virtual mesh
.PARAMETER ReplaceMaterials
Substitute materials according to materialsub.txt in content\maps
.PARAMETER NodrawTriggers
Nodraw triggers
.PARAMETER FullMinidumps
Write large minidumps on crash.
.PARAMETER EntityLimit
Fails if more than this many entities are written to the entity lump (default: no limit).

.PARAMETER StaticPropCombine
Merges static props together according to the rules defined in scripts/hammer/spcombinerules/spcombinerules.txt. This lowers the number of draw calls, increasing performance. It can also be used to lower the number of static props present in a map. See Static Prop Combine.
.PARAMETER StaticPropAutoCombine
Automatically generate static prop combine rules for props that VBSP deems should be combined. 
.PARAMETER StaticPropConsiderVis
Instead of using the distance limit, combine all props in the group that share visclusters.
.PARAMETER StaticPropSuggestRules
Lists models sharing the same material that should be added to spcombinerules.txt.
.PARAMETER StaticPropMinInstances
Set the minimum number of props in a combine group required to create a combined prop. Example: 3 for Dust 2.
.PARAMETER StaticPropPrintRules
Prints combine rules to console.
.PARAMETER StaticPropColourInstances
Colours instances of static props.
.PARAMETER StaticPropKeepSources
Don't delete the autogenerated QCs and unpacked model files after finishing.
.PARAMETER CombineIgnoreFastReflection
Combine props, even if they have differing Render in Fast Reflections settings.
.PARAMETER CombineIgnoreNormals
Combine props, even if they have differing Ignore Normals settings.
.PARAMETER CombineIgnoreNoShadow
Combine props, even if they have differing Disable Shadows settings.
.PARAMETER CombineIgnoreNoVertexLighting
Combine props, even if they have differing Disable Vertex lighting settings.
.PARAMETER CombineIgnoreNoFlashlight
Combine props, even if they have differing Disable flashlight settings.
.PARAMETER CombineIgnoreNoSelfShadow
Combine props, even if they have differing Disable Self-Shadowing settings.
.PARAMETER CombineIgnoreNoShadowDepth
Combine props, even if they have differing Disable ShadowDepth settings.

#>

function New-BSP {
    Param(
        [Parameter(Mandatory=$True)]
        [ValidateScript({
            return Test-FileValidation -Path $_ -Extensions @("vmf", "vmm");
        })]
        [string]$Path,

        # Common options
        [switch]$OnlyEnts,
        [switch]$OnlyProps,
        [switch]$GLView,
        [switch]$NoDetail,
        [switch]$NoWater,
        [switch]$LowPriority,
        [ValidateScript({
            return Test-FolderValidation -Path $_;
        })]
        [string]$PackDirectory,

        # Other options
        [string]$NumThreads,
        [switch]$VerboseEntities,
        [switch]$NoWeld,
        [switch]$NoCsg,
        [switch]$NoShare,
        [switch]$NoTJunc,
        [switch]$NoOpt,
        [switch]$NoPrune,
        [switch]$NoMerge,
        [switch]$NoMergeWater,
        [switch]$NoSubDiv,
        [string]$MicroVolume,
        [switch]$FullDetail,
        [switch]$AllDetail,
        [switch]$LeakTest,
        [switch]$BumpAll,
        [switch]$SnapAxial,
        [string[]]$Block,
        [string[]]$Blocks,
        [string]$BlockSize,
        [switch]$DumpStaticProps,
        [switch]$DumpCollide,
        [switch]$ForceSkyVis,
        [string]$LuxelScale,
        [string]$MinLuxelScale,
        [switch]$LightIfMissing,
        [switch]$LocalPhysX,
        [switch]$KeepStaleZip,
        [switch]$VirtualDispPhysics,
        [switch]$Xbox,
        [switch]$Xbox360,
        [switch]$ReplaceMaterials,
        [switch]$FullMinidumps,
        [string]$EntityLimit,

        # Static Prop Combine
        #[MinBranch("csgo")]
        [switch]$StaticPropCombine,
        #[MinBranch("csgo")]
        [switch]$StaticPropAutoCombine,
        #[MinBranch("csgo")]
        [switch]$StaticPropConsiderVis,
        #[MinBranch("csgo")]
        [switch]$StaticPropSuggestRules,
        #[MinBranch("csgo")]
        [switch]$StaticPropMinInstances,
        #[MinBranch("csgo")]
        [switch]$StaticPropPrintRules,
        #[MinBranch("csgo")]
        [switch]$StaticPropColourInstances,
        #[MinBranch("csgo")]
        [switch]$StaticPropKeepSources,
        #[MinBranch("csgo")]
        [switch]$CombineIgnoreFastReflection,
        #[MinBranch("csgo")]
        [switch]$CombineIgnoreNormals,
        #[MinBranch("csgo")]
        [switch]$CombineIgnoreNoShadow,
        #[MinBranch("csgo")]
        [switch]$CombineIgnoreNoVertexLighting,
        #[MinBranch("csgo")]
        [switch]$CombineIgnoreNoFlashlight,
        #[MinBranch("csgo")]
        [switch]$CombineIgnoreNoSelfShadow,
        #[MinBranch("csgo")]
        [switch]$CombineIgnoreNoShadowDepth
    )

    $params = Resolve-ParamList @{
        "-v" = $Verbose.IsPresent;
        "-onlyents" = $OnlyEnts.IsPresent;
        "-onlyprops" = $OnlyProps.IsPresent;
        "-glview" = $GLView.IsPresent;
        "-nodetail" = $NoDetail.IsPresent;
        "-nowater" = $NoWater.IsPresent;
        "-low" = $LowPriority.IsPresent;
        "-embed" = $PackDirectory;
        #"-dxlevel" = $DXLevel;
        
        "-threads" = $NumThreads;
        "-verboseentities" = $VerboseEntities.IsPresent;
        "-noweld" = $NoWeld.IsPresent;
        "-nocsg" = $NoCsg.IsPresent;
        "-noshare" = $NoShare.IsPresent;
        "-notjunc" = $NoTJunc.IsPresent;
        "-noopt" = $NoOpt.IsPresent;
        "-noprune" = $NoPrune.IsPresent;
        "-nomerge" = $NoMerge.IsPresent;
        "-nomergewater" = $NoMergeWater.IsPresent;
        "-nosubdiv" = $NoSubDiv.IsPresent;
        "-micro" = $MicroVolume;
        "-fulldetail" = $FullDetail.IsPresent;
        "-alldetail" = $AllDetail.IsPresent;
        "-leaktest" = $LeakTest.IsPresent;
        "-bumpall" = $BumpAll.IsPresent;
        "-snapaxial" = $SnapAxial.IsPresent;
        "-block" = $Block;
        "-blocks" = $Blocks;
        "-blocksize" = $BlockSize;
        "-dumpstaticprops" = $DumpStaticProps.IsPresent;
        "-dumpcollide" = $DumpCollide.IsPresent;
        "-forceskyvis" = $ForceSkyVis.IsPresent;
        #"-defaultluxelsize" = $DefaultLuxelSize;
        "-luxelscale" = $LuxelScale;
        "-minluxelscale" = $MinLuxelScale;
        "-lightifmissing" = $LightIfMissing.IsPresent;
        "-localphysx" = $LocalPhysX.IsPresent;
        "-keepstalezip" = $KeepStaleZip.IsPresent;
        "-virtualdispphysics" = $VirtualDispPhysics.IsPresent;
        "-xbox" = $Xbox.IsPresent;
        "-x360" = $Xbox360.IsPresent;
        "-allowdetailcracks" = $AllowDetailCracks.IsPresent;
        "-novirtualmesh" = $NoVirtualMesh.IsPresent;
        "-replacematerials" = $ReplaceMaterials.IsPresent;
        "-nodrawtriggers" = $NodrawTriggers.IsPresent;
        "-FullMinidumps" = $FullMinidumps.IsPresent;
        "-entity_limit" = $EntityLimit;
        #"-maxlightmapdim" = $MaxLightMapDim;
    }

    $params = $params + $Path;
    Invoke-SourceTool -Tool "vbsp" -Parameters $params;
}